<%@ Page Language="C#" AutoEventWireup="true" CodeFile="AddCity.aspx.cs" Inherits="AddCity" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .style1
        {
            width: 100%;
            border-style: solid;
            border-width: 5px;
        }
        .style2
        {
            width: 100%;
        }
        .style4
        {
            width: 227px;
        }
        .style5
        {
            width: 173px;
        }
        .style6
        {
            width: 16px;
        }
        .style7
        {
            width: 1218px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <table cellpadding="0" cellspacing="0" class="style1">
        <tr>
            <td bgcolor="#006699" class="style7" style="text-align: center">
                <asp:Label ID="Label5" runat="server" Text="MANAGE CITY"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;
            </td>
            <td bgcolor="#006699" style="text-align: center">
                <asp:HyperLink ID="HyperLink1" runat="server" ImageUrl="~/logos/homekey.jpg" 
                    NavigateUrl="~/AdminHome.aspx">HyperLink</asp:HyperLink>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <table class="style2">
                    <tr>
                        <td class="style6">
                            <asp:Label ID="Label4" runat="server" Text="CityName:"></asp:Label>
                        </td>
                        <td class="style4">
                            <asp:TextBox ID="txtcityname" runat="server" style="margin-left: 0px"></asp:TextBox>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: left">
                <table class="style2">
                    <tr>
                        <td class="style5">
                            <asp:Label ID="Label2" runat="server" Text="cityid :"></asp:Label>
                        </td>
                        <td>
                            <asp:TextBox ID="txtcityid" runat="server" style="margin-left: 124px"></asp:TextBox>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: left">
                <asp:Button ID="btnadd" runat="server" onclick="btnadd_Click1" 
                    Text="add city" />
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <asp:Label ID="lblmsg" runat="server" Text="Label"></asp:Label>
            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: left">
                <asp:Label ID="Label3" runat="server" Text="LIST:"></asp:Label>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                    AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" 
                    ForeColor="#333333" GridLines="None" onrowdeleting="GridView1_RowDeleting" 
                    onrowediting="GridView1_RowEditing" onrowupdating="GridView1_RowUpdating" 
                    onselectedindexchanged="GridView1_SelectedIndexChanged" 
                    onrowcancelingedit="GridView1_RowCancelingEdit">
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                    <Columns>
                        <asp:BoundField DataField="CityName" HeaderText="City Name" />
                        <asp:BoundField DataField="CityID" HeaderText="City ID" ReadOnly="True" />
                    </Columns>
                    <EditRowStyle BackColor="#999999" />
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                    <SortedAscendingHeaderStyle BackColor="#506C8C" />
                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                    <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                </asp:GridView>
            </td>
        </tr>
    </table>
    </form>
</body>
</html>
